# Generated by Django 5.1.4 on 2024-12-07 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Ders Kodu')),
                ('name', models.CharField(max_length=100, verbose_name='Ders Adı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ders',
                'verbose_name_plural': 'Dersler',
            },
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Kullanıcı Adı')),
                ('full_name', models.CharField(max_length=100, verbose_name='Ad Soyad')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Öğretim Üyesi',
                'verbose_name_plural': 'Öğretim Üyeleri',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(max_length=20, unique=True, verbose_name='Öğrenci No')),
                ('full_name', models.CharField(max_length=100, verbose_name='Ad Soyad')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Öğrenci',
                'verbose_name_plural': 'Öğrenciler',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('GUZ', 'Güz'), ('BAHAR', 'Bahar')], max_length=6, verbose_name='Dönem')),
                ('exam_type', models.CharField(choices=[('VIZE', 'Vize'), ('FINAL', 'Final'), ('BUTUNLEME', 'Bütünleme'), ('MAZERET', 'Mazeret')], max_length=10, verbose_name='Sınav Türü')),
                ('exam_date', models.DateField(verbose_name='Sınav Tarihi')),
                ('question_count', models.PositiveIntegerField(verbose_name='Soru Sayısı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course', verbose_name='Ders')),
            ],
            options={
                'verbose_name': 'Sınav',
                'verbose_name_plural': 'Sınavlar',
                'unique_together': {('course', 'semester', 'exam_type')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.lecturer', verbose_name='Öğretim Üyesi'),
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Toplam Puan')),
                ('question_scores', models.JSONField(verbose_name='Soru Bazlı Puanlar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.exam', verbose_name='Sınav')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student', verbose_name='Öğrenci')),
            ],
            options={
                'verbose_name': 'Sınav Sonucu',
                'verbose_name_plural': 'Sınav Sonuçları',
                'unique_together': {('exam', 'student')},
            },
        ),
    ]
