# Generated by Django 5.1.4 on 2024-12-07 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='question_scores',
            field=models.JSONField(blank=True, null=True, verbose_name='Soru Puanları'),
        ),
    ]
