# Generated by Django 5.1.4 on 2024-12-07 20:37

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_examresult_is_passed'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(blank=True, to='core.course', verbose_name='Aldığı Dersler'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='question_scores',
            field=models.JSONField(blank=True, null=True, validators=[core.models.validate_question_scores], verbose_name='Soru Puanları'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['exam', 'student'], name='core_examre_exam_id_08b920_idx'),
        ),
    ]
