# Generated by Django 5.1.4 on 2024-12-09 16:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_student_courses_alter_exam_question_scores_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Kazanım Açıklaması')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course', verbose_name='Ders')),
            ],
            options={
                'verbose_name': 'Ders Kazanımı',
                'verbose_name_plural': 'Ders Kazanımları',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamQuestionOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveIntegerField(verbose_name='Soru Numarası')),
                ('contribution_percentage', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Katkı yüzdesi en az 1 olmalıdır'), django.core.validators.MaxValueValidator(100, message='Katkı yüzdesi en fazla 100 olmalıdır')], verbose_name='Katkı Yüzdesi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.exam', verbose_name='Sınav')),
                ('outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.courseoutcome', verbose_name='Ders Kazanımı')),
            ],
            options={
                'verbose_name': 'Sınav Sorusu Kazanımı',
                'verbose_name_plural': 'Sınav Sorusu Kazanımları',
                'unique_together': {('exam', 'question_number', 'outcome')},
            },
        ),
    ]
