# Generated by Django 5.1.4 on 2024-12-12 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_courseoutcome_examquestionoutcome'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='exam_papers/', verbose_name='Sınav Kağıdı')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Yükleme Tarihi')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student', verbose_name='Öğrenci')),
            ],
            options={
                'verbose_name': 'Sınav Kağıdı',
                'verbose_name_plural': 'Sınav Kağıtları',
            },
        ),
    ]
