# Generated by Django 5.1.4 on 2024-12-13 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_lecturer_is_password_created_lecturer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Giriş Yapıldı'), ('LOGOUT', 'Çıkış Yapıldı'), ('EXAM_UPLOAD', 'Sınav Yüklendi'), ('STUDENT_ADD', 'Öğrenci Eklendi'), ('OUTCOME_ADD', 'Kazanım Eklendi'), ('VIEW_REPORT', 'Rapor Görüntülendi')], max_length=50, verbose_name='Eylem')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Detaylar')),
                ('ip_address', models.GenericIPAddressField(null=True, verbose_name='IP Adresi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tarih/Saat')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.lecturer', verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Kullanıcı Logu',
                'verbose_name_plural': 'Kullanıcı Logları',
                'ordering': ['-created_at'],
            },
        ),
    ]
